# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Anderton
email: dwanderton+jb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Occasional athlete. Obsessive learner. PhD in Getting Stuff Done. Lets explore,
  learn, and discover together!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dwanderton.github.io" # the base hostname & protocol for your site
twitter_username: false
github_username:  dwanderton
stackoverflow_userurl: 3700836/david-anderton

# Build settings
markdown: kramdown
